=== nesti13/kyar/xml2/схема.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
 <xs:element name="my">
 <xs:complexType>
 <xs:sequence>
 <xs:element name="univer" type="xs:string"/>
 <xs:element name="spec" type="xs:string"/>
 <xs:element name="score" type="xs:string"/>
 <xs:element name="plan" type="xs:string"/>
 <xs:element name="city" type="xs:string"/>
 </xs:sequence>
 </xs:complexType>
 </xs:element>
</xs:schema>

=== nesti13/kyar/xml2/xml_схема.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="1.css" ?>
<my xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="схема.xsd">
<univer>БГТУ</univer>
<spec>Программное обеспечение информационной безопасности мобильных систем</spec>
<score>300</score>
<plan>60</plan>
<city>Минск</city>
<univer>БГУИР</univer>
<spec>Программируемые мобильные системы</spec>
<score>331</score>
<plan>60</plan>
<city>Минск</city>
<univer>БГУ</univer>
<spec>Математическое и программное обеспечение мобильных устройств</spec>
<score>331</score>
<plan>60</plan>
<city>Минск</city>
</my>
